plugins {
    id 'com.android.application'
}

android {
    namespace "com.grace.app"
    compileSdk 34

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    defaultConfig {
        applicationId "com.grace.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.4"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {

        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            versionNameSuffix "_debug_" + getTimeStamp()

            buildConfigField "String", "BASE_URL", getLocalProperty('baseUrlDev')
            buildConfigField "String", "USERNAME", getLocalProperty('usernameDev')
            buildConfigField "String", "PASSWORD", getLocalProperty('passwordDev')
        }

        release {
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            buildConfigField "String", "BASE_URL", getLocalProperty('baseUrlProd')
            buildConfigField "String", "USERNAME", getLocalProperty('usernameProd')
            buildConfigField "String", "PASSWORD", getLocalProperty('passwordProd')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

def getLocalProperty(propertyName) {
    def value = project.findProperty(propertyName)
    if (value == null) {
        def localProperties = project.rootProject.file('local.properties')
        if (localProperties.exists()) {
            Properties properties = new Properties()
            localProperties.withInputStream { stream ->
                properties.load(stream)
            }
            value = properties.getProperty(propertyName, null)
        }
    }
    if (value == null) {
        return "null"
    }
    if (value.startsWith('"') && value.endsWith('"')) {
        return value
    }
    return "\"${value}\""
}


def getTimeStamp() {
    def date = new Date()
    def formattedDate = date.format('dd.MM.yyyy')
    return formattedDate
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    testImplementation 'junit:junit:4.13.2'

    /* Dagger 2.0 */
    annotationProcessor 'com.google.dagger:dagger-compiler:2.50'
    implementation 'com.google.dagger:dagger:2.50'

    /* Support */
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    /* Retrofit 2.0 */
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    /* Glide */
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    /* Material Ripple */
    implementation 'com.balysv:material-ripple:1.0.2'

    /* EventBus */
    implementation 'org.greenrobot:eventbus:3.3.1'

    /* PhotoView */
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'

    /* Widget dots */
    implementation 'com.github.uDevel:widgetlab:0.9.1'

    /* Calligraphy */
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'

    /* AutofitTextView */
    implementation 'com.github.AndroidDeveloperLB:AutoFitTextView:4'

    /* Multidex */
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation "com.google.mlkit:image-labeling:17.0.9"

}
